spring:
    application:
        name: Football-manager

    datasource:
        url: ${DB_URL:jdbc:postgresql://localhost:5432/football-manager}
        username: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:123456789}

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: false
        properties:
            hibernate:
                format_sql: false

    flyway:
        enabled: true
        baseline-on-migrate: true
        locations: classpath:db/migration

server:
    servlet:
        context-path: /api/v1

transfer:
    price:
        coefficient: ${TRANSFER_PRICE_COEFFICIENT:100000}